apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: dXNlcg==      # base64 of 'user'
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=  # base64 of 'password'
