apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-spring
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-spring
  template:
    metadata:
      labels:
        app: student-spring
    spec:
      containers:
      - name: app
        image: khalildridi9/student-management:latest
        ports:
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: spring-config
        - secretRef:
            name: spring-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  selector:
    app: student-spring
  type: NodePort
  ports:
  - port: 8089
    targetPort: 8089
    nodePort: 30080   # ou laisse Kubernetes choisir (ex: 30080)
